project:
  type: book
  output-dir: ../../docs

book:
  title: "Optimal Transport on Categorical Data for Counterfactuals using Compositional Data and Dirichlet Transport"
  author:
  - name: Arthur Charpentier
    orcid: 0000-0003-3654-6286
    affiliations:
      - name: Université du Québec à Montréal
  - name: Agathe Fernandes Machado
    orcid: 0009-0002-9743-9708
    affiliations:
      - name: Université du Québec à Montréal
  - name: Ewen Gallic
    orcid: 0000-0003-3740-2620
    affiliations:
      - name: Aix-Marseille School of Economics, Aix-Marseille Univ.
  date: "01/26/2025"
  chapters:
    - index.qmd
    - application-toydataset.qmd
    - application-german-credit.qmd
    - application-adult.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/fer-agathe/transport-simplex
        aria-label: GitHub

bibliography: ./biblio.bib

fig-cap-location: top

format:
  html:
    theme: litera
    html-math-method: mathjax
    include-in-header:
    - file: mathjax-color.html

filters:
  - pseudocode

editor: source
